### ISSUE TITLE
Idea: Markov chain in private chat [low prio]

### ISSUE THREAD

**Issue by anlutro** [LaravelIO/LioBot#5]
Markov chains make for great entertainment when it comes to chat bots, and could be something to implement for private messages.

These bots basically learn from existing text (either pre-loaded or from messages received via chat) and construct new ones based on patterns found in existing text.

This might be a lot of work if there aren't any existing libraries for it out there, and is not part of core functionality.

**Comment by mikedugan** [comment]
@machuga can this be closed? Don't see it happening anytime soon
