### ISSUE TITLE
Docs Adjustments

### ISSUE THREAD

**Issue by lagbox** [laravelio/LioBot#54]
Adjust the docs script to use redis vars for the 'default_version'. This will let us update these docs once more and from then on we can adjust the current version via redis instead of modifying the script directly when new versions come out.

**Comment by lagbox** [comment]
@machuga can someone setup a var on the server and let me know what that var is named, and I will update the script.

should be set to 5.1 atm.

**Comment by machuga** [comment]
It's just a file store. We can prob just tell the brain to remember it and pull from there?

**Comment by lagbox** [comment]
Yea that would work.

**Comment by lagbox** [comment]
I will put this feature into place shortly, since the brain is way easier to deal with than originally expected.
Main concern is our issue with google search, I am afraid we have to change search engines.

**Comment by dshoreman** [comment]
Either that or the server, tough to say without knowing if there are 
errors, or what response the bot is getting from Google.

Could you get an account created on the liona server to let you test 
from that IP, in case of captcha etc? It's known to work other places, 
just a matter of figuring out why it doesn't work here =\

**Comment by lagbox** [comment]
I have made the target version dynamic by using the brain.
Also have added the ability to switch out google for bing on demand.
