### ISSUE TITLE
add !ask to Liona

### ISSUE THREAD

**Issue by rajlaksh** [LaravelIO/LioBot#58]
Please add !ask command to Liona so it show message Don't Ask Just Ask.

**Comment by machuga** [comment]
This already exists as !dataja, I think !ask has been trained to do it.  Just ask one of the ops in the room and it can be added in memory - doesn't need to be a PR.

**Comment by rajlaksh** [comment]
!ask show ya I got nothing for !ask.

**Comment by machuga** [comment]
Rizqi can add it if needed. Liona has a built in data store.

**Comment by rajlaksh** [comment]
thanks
