### ISSUE TITLE
Docs search

### ISSUE THREAD

**Issue by lagbox** [laravelio/LioBot#61]
Seems broken again (no results). I will have to play around with it later and see what is up. 
Was working yesterday :).

**Comment by lagbox** [comment]
Well it seems to be working fine now and gets the php results correctly.
voodoo ?

**Comment by lagbox** [comment]
And again not working ... do we have some request limits or something ?

**Comment by machuga** [comment]
I have no idea. Not daily for sure.

**Comment by lagbox** [comment]
This is still not working correctly on the server. After having others test, there is a 302 response coming back from google with a redirect for some people. Im guessing we need to adjust this to follow that.

**Comment by lagbox** [comment]
PR #64 closes this
