### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by driesvints** [laravelio/LioBot#75]
@laravelio/liobot hey LioBot team 🙂

I'd like to rename the repo to `lio-bot` if that's alright to be more in sync with the other organisation repositories. 

Is that ok with you?

**Comment by machuga** [comment]
Let's just switch it to 'liona' so it matches its handle in IRC

**Comment by driesvints** [comment]
Sounds good!

**Comment by driesvints** [comment]
Done. I'll rename the Github team as well.
